[versions]
idea = "221.6008.13"
kotlin = "1.8.22"
ktlint = "0.49.1"
spotless = "6.19.0"
sqldelight = "2.0.0-rc01"
sql-psi = "0.4.3"

[libraries]
intellij-analysis = { module = "com.jetbrains.intellij.platform:analysis-impl", version.ref = "idea" }
intellij-util = { module = "com.jetbrains.intellij.platform:util", version.ref = "idea" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
sql-psi-test-fixtures = { module = "com.alecstrong.sql.psi:test-fixtures", version.ref = "sql-psi" }
sqldelight-postgresql-dialect = { module = "app.cash.sqldelight:postgresql-dialect", version.ref = "sqldelight" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
