name: Lint Project

on:
  pull_request:

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup
    - name: Lint Project
      run: ./gradlew spotlessCheck
