name: Lint Project

on:
  pull_request:

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run Spotless
      run: ./gradlew spotlessCheck
