name: Run Tests on Project

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
